export const experience = [
  {
    number: '01',
    slug: 'cincinnati-ai',
    company: 'Cincinnati AI',
    role: 'Software Engineer · Backend Integrations',
    period: 'Nov 2024 – Present',
    location: 'Atlanta, Georgia',
    summary: 'Backend integrations with Laravel, Docker-based services, RAG workflows, and client-facing experiences across web and iOS.',
    overview: 'I build the integration layer between client applications and backend services, and contribute to web and iOS features that use those APIs.',
    highlights: [
      'Developed backend integration workflows using PHP and Laravel, including facade services that abstract communication between client applications and Docker-based microservices.',
      'Implemented RESTful API endpoints for workspace, channel, and message workflows, enabling integration with Laravel web clients, React interfaces, and iOS applications.',
      'Implemented RAG-based internal workflows using PHP and API integrations to support document retrieval, contextual data access, and AI-assisted product features.',
      'Designed service-layer architecture, API client abstractions, environment-based configuration, and reusable integration patterns to improve maintainability and scalability.',
      'Built a lightweight Laravel Breeze-based interface using Blade and Tailwind CSS to test, validate, and interact with backend and chat-related features.',
      'Developed frontend and client-facing features using React, Swift, UIKit, SwiftUI, Combine, and REST API integrations.',
      'Integrated Firebase, Core Data, MapKit, and REST APIs to support authentication, local persistence, location-based features, and backend communication.',
      'Used Docker, cURL, Postman, Git, and GitHub to support local development, API validation, debugging, and version control.',
      'Improved application stability through unit testing, code reviews, debugging, logging, and engineering best practices.',
      'Optimized performance and data handling, reducing load times and improving responsiveness across key user flows.',
      'Mentored junior developers on Git/GitHub/GitLab workflows, API integration, Laravel basics, Swift, Combine, Core Data, and software architecture.',
      'Created training documentation and study guides, reducing junior developer onboarding time by 30–50%.',
    ],
    tags: ['PHP / Laravel', 'REST APIs', 'RAG', 'React', 'Swift', 'Docker'],
  },
  {
    number: '02',
    slug: 'walmart-global-tech',
    company: 'Walmart Global Tech',
    role: 'Senior iOS Developer · Cart & Checkout Team',
    period: 'Aug 2025 – Apr 2026',
    location: 'Sunnyvale, California',
    summary: 'iOS cart and checkout features, GraphQL integrations, accessibility improvements, and production reliability for a high-traffic commerce app.',
    overview: 'On the Cart & Checkout team, I built and maintained customer-facing iOS experiences and helped stabilize critical purchase flows through cross-team validation and production debugging.',
    highlights: [
      'Built and maintained API-driven iOS features for cart and checkout flows in a high-traffic e-commerce application.',
      'Improved critical purchase flows by enhancing checkout consistency, user-facing behavior, release readiness, and production reliability.',
      'Resolved production issues involving date handling, user-facing error messaging, analytics payloads, image rendering, fulfillment logic, and address validation.',
      'Extended GraphQL fragments to support new mobile product capabilities, coordinating multiple PRs and cross-team validation for safer rollout.',
      'Implemented CCM feature flags to control tenant-specific behavior for Sam’s Club U.S. without impacting other Walmart tenants.',
      'Supported the beta rollout of a new fulfillment experience within cart and checkout, contributing to implementation, validation, debugging, and release stabilization across the U.S. market.',
      'Improved accessibility across cart and checkout experiences by supporting VoiceOver and ADA-aligned behavior for headers, loading states, carousels, grouped content, filters, snackbars, bottom sheets, image links, and focus restoration.',
      'Enhanced Shoppable Lists and product-related flows by fixing quantity labels, replacement controls, multi-selection feedback, WCP component behavior, bundled items, and Add to Cart interactions.',
      'Resolved UI consistency issues across Auto Layout, banners, placeholders, spacing, alignment, reusable components, and dynamic content.',
      'Applied SOLID principles, MVVM-C, delegation, protocol-oriented programming, reusable component patterns, and clean architecture practices to deliver maintainable iOS code.',
    ],
    tags: ['Swift', 'GraphQL', 'VoiceOver', 'MVVM-C', 'Feature flags'],
  },
  {
    number: '03',
    slug: 'transom',
    company: 'Transom',
    role: 'Software / IoT Engineer',
    period: 'Jun 2022 – Oct 2024',
    location: 'San Luis Potosí, Mexico',
    summary: 'Real-time SCADA dashboards for airport infrastructure, SQL-backed monitoring, and PLC-integrated industrial systems.',
    overview: 'At Transom, I developed monitoring and data systems for airport infrastructure and industrial operations, alongside modernization of legacy applications.',
    highlights: [
      'Designed and deployed real-time SCADA dashboards and data models for SFO and LaGuardia airport infrastructure, processing 300,000+ BACnet and OPC field signals.',
      'Integrated SQL Server with monitoring platforms to support operational reporting, alarms, historical analysis, and predictive maintenance workflows.',
      'Refactored legacy C and Visual Basic systems and developed a Siemens PLC-integrated monitoring solution, improving maintainability and visibility into production timing and throughput.',
    ],
    tags: ['SCADA', 'SQL Server', 'BACnet', 'OPC', 'PLC'],
  },
] as const;
