export const experience = [
  {
    number: '01',
    slug: 'cincinnati-ai',
    company: 'Cincinnati AI',
    role: 'Software Engineer · Backend Integrations',
    period: 'Nov 2024 – Present',
    location: 'Atlanta, Georgia',
    summary: 'I develop a client-facing product across an iOS app, Laravel APIs, and a web interface, connecting product workflows from the UI to backend services.',
    overview: 'My work at Cincinnati AI connects mobile and web experiences with the services behind them. I lead development across the iOS application, a PHP/Laravel integration layer, and a lightweight interface used to exercise and validate chat workflows.',
    highlights: [
      'Built a Laravel facade and service layer with REST endpoints for workspace, channel, and message workflows consumed by web and iOS clients.',
      'Created a Blade and Tailwind CSS interface with Laravel Breeze to validate chat behavior across the full request lifecycle.',
      'Integrated authentication, persistence, location, and backend-driven flows in the iOS app using Swift, UIKit, SwiftUI, Combine, Core Data, Firebase, MapKit, and REST APIs.',
      'Improved reliability through unit tests, code review, logging, API validation, performance work, and structured debugging.',
      'Mentored junior developers and wrote documentation that reduced onboarding time by 30–50%.',
    ],
    tags: ['Laravel', 'REST APIs', 'Swift', 'SwiftUI', 'Docker'],
  },
  {
    number: '02',
    slug: 'walmart-global-tech',
    company: 'Walmart Global Tech',
    role: 'Senior iOS Engineer · Cart & Checkout',
    period: 'Aug 2025 – May 2026',
    location: 'Sunnyvale, California',
    summary: 'I delivered iOS features for cart and checkout, integrating GraphQL data, building reusable purchase flows, and supporting safe releases.',
    overview: 'On the Cart & Checkout team, I worked on customer-facing iOS experiences where purchase flows needed to remain dependable during feature delivery. I collaborated with product, design, QA, backend, and mobile engineers from scoping through release stabilization.',
    highlights: [
      'Extended GraphQL fragments and client integrations to support new product functionality, coordinating changes across pull requests and teams.',
      'Implemented feature flags for tenant-specific behavior and helped roll out a new fulfillment option without disrupting existing delivery experiences.',
      'Built item-variant and bundled-product experiences in Swift with reusable components and MVVM-C patterns.',
      'Investigated production issues involving analytics, dates, address validation, images, fulfillment, calculations, and user-facing errors.',
      'Used code reviews, testing, logging, and quality tools to reduce regression risk during releases.',
    ],
    tags: ['Swift', 'GraphQL', 'MVVM-C', 'Feature flags', 'iOS'],
  },
  {
    number: '03',
    slug: 'transom',
    company: 'Transom',
    role: 'Software / IoT Engineer',
    period: 'Jun 2022 – Oct 2024',
    location: 'San Luis Potosí, Mexico',
    summary: 'I built industrial monitoring and data systems, including airport SCADA dashboards, SQL-backed reporting, and PLC-integrated production monitoring.',
    overview: 'At Transom, I worked at the intersection of software, industrial systems, and operational data. The work ranged from airport infrastructure monitoring to modernizing legacy applications and making production data easier to observe.',
    highlights: [
      'Designed real-time SCADA dashboards and data models for SFO and LaGuardia airport infrastructure, processing more than 300,000 BACnet and OPC field signals.',
      'Connected SQL Server to monitoring platforms for reporting, alarms, historical analysis, and predictive-maintenance workflows.',
      'Refactored legacy C and Visual Basic systems to improve maintainability.',
      'Developed a Siemens PLC-integrated monitoring solution to improve visibility into production timing and throughput.',
    ],
    tags: ['SCADA', 'SQL Server', 'BACnet', 'OPC', 'PLC'],
  },
] as const;
