export const projects = [
  {
    number: '01',
    category: 'Professional experience',
    title: 'Cart & Checkout systems',
    description: 'Backend and frontend work in commerce, including API design, pricing behavior, data consistency, and performance investigation.',
    detail: 'My work on a Cart and Checkout team has involved designing service behavior around bundles and pricing, serving data to frontend consumers, and investigating relational database performance. I enjoy the boundary where a technical decision affects a customer journey.',
    tags: ['Java', 'Spring Boot', 'GraphQL', 'PostgreSQL'],
    note: 'High-level description; proprietary implementation details are intentionally omitted.',
  },
  {
    number: '02',
    category: 'Independent project · in progress',
    title: 'PS Portal game explorer',
    description: 'An iOS learning project for exploring games available through PlayStation Portal cloud streaming.',
    detail: 'I am using this project to practice SwiftUI, UIKit, MVVM, networking, and API integration. The aim is a useful browsing experience while strengthening my iOS engineering skills. Availability data and its source need validation before a public release.',
    tags: ['Swift', 'SwiftUI', 'UIKit', 'MVVM'],
    note: 'In progress; no published app or repository is claimed.',
  },
  {
    number: '03',
    category: 'University research',
    title: 'ns-3 + AI research setup',
    description: 'A documented setup for connecting network simulation in ns-3 with Python-based AI tooling.',
    detail: 'Developed with José Saúl Castillo Ipiña during a machine learning course. Our goal was to understand the simulator, install the ns3-ai module, and document the environment so that experiments could be reproduced. The repository contains the installation guide and reports.',
    tags: ['Networking', 'Python', 'Simulation', 'Documentation'],
    href: 'https://github.com/GabrielVillagran/ns3-ai',
    note: 'An academic project from 2022; the installation guide targets Ubuntu 20.04.',
  },
  {
    number: '04',
    category: 'Independent project · in progress',
    title: 'Michoacana recipe API',
    description: 'A practice project for modeling and serving paleta and agua fresca recipes through a Spring Boot API.',
    detail: 'I am building this project to practice clean API boundaries, data modeling, and a React frontend that can consume the service. It is an exercise in product design and implementation, not a production recipe catalog.',
    tags: ['Spring Boot', 'Java', 'React', 'API design'],
    note: 'In progress; content and licensing will be checked before public release.',
  },
];
