baseURL = "https://gabrielvillagran.github.io/my_launchx_blog/"
languageCode = "en-us"
title = "Bitácora de Explorer: Gabriel Villagran"
theme = "hugo-winston-theme"
relativeURLs = true
canonifyURLs = true

pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true
paginate = 3

[params]
  google_analytics_id = "UA-225486122-1"
  # Hey Explorer aquí pon tu twitter 👇
  twitter_handle = "@Gabriel29A6"
  showAuthorOnHomepage = true
  showAuthorOnPosts = false
  showPostsOnHomepage = false
  addFrame = true
  addDot = true
